### ISSUE TITLE
HAML and YAML support

### ISSUE THREAD

**Issue by svyatogor** [biletskyy/flatwhite-syntax#18]
I totally LOVE the theme. But could you add support for YAML and HAML files?

**Comment by biletskyy** [comment]
Thank you for your kind words.
I added YAML support, but it's not much to highlight there.
I also added HAML support, please, have a look and tell me if this is ok. It looks too colorful for my taste because mostly everything is highlighted. That's not how I like it, but i'm not sure how to do it differently.
