### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by Willamin** [biletskyy/flatwhite-syntax#7]
It was working, but as I started working today, everything between `<?php` and `?>` is highlighted orange.

**Comment by biletskyy** [comment]
Thank you for interest in this theme. I understand the issue. Recently I changed embedded highlighting because in most cases embeds are very simple and they don't need highlighting inside. 
But it is different in PHP. So i fixed this, also added better PHP support.

Also added settings to make it possible to use full highlighting in any embeds.
